# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_room'),
        ('accounts', '0002_auto_20171020_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='policy.Room'),
        ),
    ]
