version: '3'

services:
  django:
    container_name: api
    env_file:
      - environments/mysql.env
      - environments/oauth.env
      - environments/settings.env
      - environments/secret.env
    restart: always
    image: icists/ams2-api
    build:
      context: ./django
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./django:/code
      - static:/static
    environment:
      DATABASE_URL: 'mysql'
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    env_file:
      - environments/mysql.env
      - environments/secret.env
    restart: always
    image: mysql:8.0
    volumes:
      - mysql-persistent-volume:/var/lib/mysql
    expose:
      - "3306"

  nginx:
    container_name: nginx
    restart: always
    image: icists/ams2-nginx
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/certs:/etc/certs
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - static:/static
    links:
      - django:django
      - web-vue:web-vue

  web-vue:
    image: icists/ams2-web
    container_name: web-vue
    restart: always
    build: ./web/
    command: npm start
    environment:
      PORT: 8080
      HOST: dev.icists.org
    volumes:
      - ./web:/code
      - node_modules:/code/node_modules

volumes:
  mysql-persistent-volume:
  static:
  node_modules:
