version: '3'

services:
  django:
    env_file:
      - environments/db.env
      - environments/oauth.env
      - environments/entrypoint.env
    restart: always
    build:
      context: ./django
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./django:/code
    environment:
      DATABASE_URL: 'mysql'
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mysql

  mysql:
    env_file:
      - environments/db.env
    restart: always
    build:
      context: ./mysql
    volumes:
      - mysql-persistent-volume:/var/lib/mysql
    expose:
      - "3306"

volumes:
  mysql-persistent-volume:
