version: '3'

services:
  django:
    container_name: django
    env_file:
      - environments/mysql.env
      - environments/oauth.env
      - environments/settings.env
      - environments/secret.env
    restart: always
    build:
      context: ./django
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./django:/code
      - static:/static
    environment:
      DATABASE_URL: 'mysql'
      DEBUG: 'True'
      DJANGO_MANAGEPY_MIGRATE: 'on'
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    env_file:
      - environments/mysql.env
      - environments/secret.env
    restart: always
    image: mysql:8.0.3
    volumes:
      - mysql-persistent-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

  web:
    container_name: web
    build: ./web/
    command: npm start
    environment:
      PORT: 8080
      HOST: 'localhost'
      API_HOST: 'http://django'
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./web:/code
      - web-dist:/code/dist

volumes:
  mysql-persistent-volume:
  static:
  web-dist:
