# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_auto_20171102_0411'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='breakfast_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pre_option',
        ),
        migrations.AddField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='orders', to='policy.Price'),
        ),
    ]
