# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171102_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='essay_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='policy.EssayTopic'),
        ),
        migrations.AlterField(
            model_name='application',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='registration.Group'),
        ),
        migrations.AlterField(
            model_name='application',
            name='topic_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='policy.ProjectTopic'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
