# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180418_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='policy.AccommodationOption'),
        ),
    ]
