# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import policy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('num_rooms', models.PositiveSmallIntegerField(verbose_name='number of rooms')),
                ('price_krw', models.PositiveIntegerField(verbose_name='price in KRW')),
                ('price_usd', models.PositiveIntegerField(verbose_name='price in USD')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=11, validators=[policy.models.swift_code_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('krw', models.PositiveIntegerField(verbose_name='in KRW')),
                ('usd', models.PositiveIntegerField(verbose_name='in USD')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BE', 'Before Early'), ('ES', 'Early'), ('EC', 'Early Closed'), ('RS', 'Regular'), ('RC', 'Regular Closed'), ('LS', 'Late'), ('LC', 'Late Closed')], max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
