# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('BE', 'Before Early'), ('EO', 'Early Open'), ('EC', 'Early Closed'), ('RO', 'Regular Open'), ('RC', 'Regular Closed'), ('LO', 'Late Open'), ('LC', 'Late Closed')], max_length=2),
        ),
    ]
