# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20171022_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='krw',
        ),
        migrations.RemoveField(
            model_name='price',
            name='usd',
        ),
        migrations.AddField(
            model_name='accommodationoption',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price_krw',
            field=models.PositiveIntegerField(default=0, verbose_name='price in KRW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price_usd',
            field=models.PositiveIntegerField(default=0, verbose_name='price in USD'),
            preserve_default=False,
        ),
    ]
