# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20171022_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.AccommodationOption')),
            ],
        ),
    ]
