# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20171025_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationoption',
            name='price_krw_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KRW', 'KRW'), ('USD', 'USD')], default='KRW', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='accommodationoption',
            name='price_usd_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KRW', 'KRW'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='price',
            name='price_krw_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KRW', 'KRW'), ('USD', 'USD')], default='KRW', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='price',
            name='price_usd_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KRW', 'KRW'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='price_krw',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='KRW', max_digits=7),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='price_usd',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=4),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_krw',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='KRW', max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_usd',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=4),
        ),
    ]
