# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_auto_20171025_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='min_group_size',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='minimum group size'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='current_stage',
            field=models.CharField(choices=[('BE', 'Before Early'), ('E', 'Early'), ('EC', 'Early Closed'), ('R', 'Regular'), ('RC', 'Regular Closed'), ('L', 'Late'), ('LC', 'Late Closed')], default='BE', max_length=2),
        ),
    ]
