# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:11
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import policy.models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_auto_20171025_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'other configurations'},
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='price_krw',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='KRW', max_digits=7, validators=[policy.models.CurrencyValidator('KRW')], verbose_name='price in KRW'),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='price_usd',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=4, validators=[policy.models.CurrencyValidator('USD')], verbose_name='price in USD'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_krw',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='KRW', max_digits=7, validators=[policy.models.CurrencyValidator('KRW')], verbose_name='price in KRW'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_usd',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=4, validators=[policy.models.CurrencyValidator('USD')], verbose_name='price in USD'),
        ),
    ]
