# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_auto_20171102_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policy.AccommodationOption'),
        ),
    ]
