version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: icistsdb
    restart: always
    image: mysql/mysql-server:8.0
    expose:
      - "3306"
  ams2:
    environment:
      DJANGO_MANAGEPY_MIGRATE: 'on'
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
